### ISSUE TITLE
How to remove the "Add row" button?

### ISSUE THREAD

**Issue by maykino** [fooplugins/FooTable#487]
I only allow to edit the existing data. How do I remove the "Add row" button?

**Comment by steveush** [comment]
Hi,

The easiest way at the moment is to simply hide the button with some CSS but I will definitely look at adding this in as an option so the button is simply never even rendered.

There are two ways you could do this, the first is the correct way using a more specific CSS selector to override the `display` property like the below:

``` css
table.footable.footable-editing.footable-editing-show button.footable-add {
    display: none;
}
```

Otherwise the shortcut is to just specify the `!important` modifier like the below:

``` css
button.footable-add {
    display: none !important;
}
```

Thanks
