### ISSUE TITLE
Hide page label

### ISSUE THREAD

**Issue by stavrianosy** [fooplugins/FooTable#506]
What is the best way to hide/remove the the grey page label?

![image](https://cloud.githubusercontent.com/assets/2734457/17789300/53111242-659a-11e6-9cf2-e92823bebdc7.png)

Is there a better way other than pure jquery?

**Comment by steveush** [comment]
Hi,

You should be able to hide it using just a little bit of CSS, the below should do the trick if you include it after the main FooTable CSS files.

``` css
table.footable>tfoot>tr.footable-paging>td>span.label {
    display: none;
}
```

Thanks
