### ISSUE TITLE
way to customize paging widget?

### ISSUE THREAD

**Issue by jonaumann** [fooplugins/FooTable#625]
The paging component will wrap on mobile phones, that is kind of ugly :-) Is there a way to make it more customizable so that it fits on a xs screen without wrapping? For example, not all buttons might be needed (the ... buttons could collapse) or the whole widget could collapse into something more compact like only << | >>.

![image](https://cloud.githubusercontent.com/assets/24921722/24111452/b77f8b74-0d96-11e7-975f-f8311adb07dc.png)

**Comment by steveush** [comment]
Hi @jonaumann,

I was so sure I had done that for paging but apparently I have not ;) I'll see what I can do for the next release to make the buttons into something a bit more xs friendly.  In the mean time you can show/hide what you like on the xs breakpoint using the below CSS:

```css
.footable.breakpoint-xs ul.pagination li[data-page="first"],
.footable.breakpoint-xs ul.pagination li[data-page="prev"],
.footable.breakpoint-xs ul.pagination li[data-page="prev-limit"],
.footable.breakpoint-xs ul.pagination li[data-page="next-limit"],
.footable.breakpoint-xs ul.pagination li[data-page="next"],
.footable.breakpoint-xs ul.pagination li[data-page="last"],
.footable.breakpoint-xs ul.pagination li.footable-page {
	display: none;
}
```

The above will hide all the buttons and page numbers, remove the ones you want to show from the selector.

Thanks
